spring.data.mongodb.uri: "mongodb://localhost/mongodumper"
spring.mvc.static-path-pattern: /**
spring.resources.static-locations: file:src/main/resources/static/, classpath:/static/
mongodumper.mongodump: "mongodump"